### ISSUE TITLE
support CIDv1

### ISSUE THREAD

**Issue by hybla0** [IOsetting/ipfs-gateway-selector#1]
Currently if a CIDv1 is given in input it gets truncated

**Comment by IOsetting** [comment]
Could you please provide some CIDv1 codes that I can reproduce this issue? 

I just tried the CIDv1 sample code from [docs.ipfs.io](https://docs.ipfs.io/concepts/content-addressing/) `bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi`, you can test with the link below:  
https://ipfs.io/ipns/ipnso.com/?cid=bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi

**Comment by hybla0** [comment]
hi, for a moment i thought the issue was solved seeing the behavior with the cid you provided, but i tried these 10 cids:

`bafykbzaceaeofefgje22l7rhgtcgs22m32f4ysw5nqa3ty5zawfovqam7pj2c
bafykbzacec26l2xeok4xwa3bsuyn5bw7wismuiyudfbgqsozcsicwej4suqhi
bafykbzaceawawzsvi4gne4vquoi2vuqkgfd4ubqhfw6twoi2bpggdq5iopdpa
bafykbzacedvmnue2vtptbxz5wpxveggcj7xunwjwm22cqxmnqzpybsebzt5ii
bafykbzacea6kjyayrx7kj26uriosbih7pbzrkvkzpnycsdmtqf3vyhyfp24ky
bafykbzacecwysablchj6hdqfa6u2iava3vexr57tgtpv4o23x34w2n4v2nuyy
bafykbzacedgloh6pikhbrvcu4xi5hv6cnn5h2crtcarznpsdfjrde7p26ffo6
bafykbzacebhfuun2iotdvg3ldlhy4beq5ht7qkpjxm5ln6sgrncuit76nkyrm
bafykbzaceavmnht5dhgze55scf2rreutnst4ii7tmyfl3whuyey4luytptfya
bafykbzaceb4abgamx67nd6siw3rql73qfms6n4n6wreoy4z4k6i3wnhy75kxq`

i don't know why but they have more characters than the cid you provided, so it gets truncated

**Comment by IOsetting** [comment]
Thank you! I will fix this.

**Comment by IOsetting** [comment]
This has been fixed
